export default {
  FETCH_BEER: 'FETCH_BEER',
  FETCH_BEER_SUCCESS: 'FETCH_BEER_SUCCESS',
  ADD_BEER: 'ADD_BEER',
  ADD_BEER_SUCCESS: 'ADD_BEER_SUCCESS',
  REMOVE_BEER: 'REMOVE_BEER',
  REMOVE_BEER_SUCCESS: 'REMOVE_BEER_SUCCESS',
  BEER_ERROR: 'BEER_ERROR'
}
