export default {
  FETCH_COIN: 'FETCH_COIN',
  FETCH_COIN_SUCCESS: 'FETCH_COIN_SUCCESS',
  ADD_COIN: 'ADD_COIN',
  ADD_COIN_SUCCESS: 'ADD_COIN_SUCCESS',
  REMOVE_COIN: 'REMOVE_COIN',
  REMOVE_COIN_SUCCESS: 'REMOVE_COIN_SUCCESS',
  COIN_ERROR: 'COIN_ERROR'
}
