export const CLOUD='cloud'
export const CLOUDY='cloudy'
export const SUN='day-sunny'
export const RAIN='rain'
export const WINDY='windy'
export const SNOW='snow'
export const THUNDER = 'thunder'
export const DRIZZLE = 'cloudy'
